ajaxindjango/urls.py
from django.contrib import admin
from django.urls import path
from my_app.views import (
    indexView,
    postPerson,
    checkNickName
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name='home'),
    path('post/ajax/person', postPerson, name='post_person'),
    path('get/ajax/validate/nickname', checkNickName, name='validate_nickname'),
]

my_app/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    nick_name       = models.CharField(max_length=100, unique=True)
    first_name      = models.CharField(max_length=100)
    last_name       = models.CharField(max_length=100)
    address         = models.CharField(max_length=150)

    def __str__(self):
        return self.nick_name

my_app/forms.py
from django import forms

from .models import Person

class PersonForm(forms.ModelForm):
    class Meta:
        model   = Person
        fields  = ('__all__')

my_app/views.py
from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import render

from .models import Person
from .forms import PersonForm

# Create your views here.
def indexView(request):
    form        = PersonForm()
    template    = 'index.html'
    context     = {
         'person': Person.objects.all(),
         'form': form,
    }
    
    return render(request, template, context)

def postPerson(request):
    # request harus ajax dan methodnya harus POST
    if request.is_ajax and request.method    ==  "POST":
        # ambil data form
        form    = PersonForm(request.POST)
        # simpan data dan ambil object dari instance
        if form.is_valid():
            instance    = form.save()
            # sambungkan object person baru di json
            ser_instance    = serializers.serialize('json', [instance, ])
            # kirim ke sisi client
            return JsonResponse({'instance': ser_instance}, status=200)
        else:
            # beberapa pesan form kesalahan ditambahkan
            return JsonResponse({'error': form.errors}, status=400)
    # beberaoa error ditambahkan
    return JsonResponse({'error': ''}, status=400)

def checkNickName(request):
    # requestnya harus ajax dan method nya harus GET
    if request.is_ajax and request.method == 'GET':
        # ambil nickname dari clientside
        nick_name = request.GET.get("nick_name", None)
        # cek nick_name di database
        if Person.objects.filter(nick_name = nick_name).exists():
            # jika nick_name ditemukan
            return JsonResponse({"valid":False}, status=200)
        else:
            return JsonResponse({"valid":True}, status = 200)
    return JsonResponse({}, status = 400)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}

<h1 class="text-center">AJAX di Django</h1>

<div class="container-fluid">
    <form id="person-form">
        {% csrf_token %}
        <div class="form-group col-4">
            <div class="row">
                <div class="col">
                    {% render_field form.nick_name class+="mb-2 form-control" placeholder="Nick Name" %}
                    {% render_field form.first_name class+="mb-2 form-control" placeholder="First Name" %}
                </div>
                <div class="col">
                    {% render_field form.last_name class+="mb-2 form-control" placeholder="Last Name" %}
                    {% render_field form.address class+="mb-2 form-control" placeholder="Address" %}
                </div>
            </div>
        </div>
        <input type="submit" class="mb-2 mt-2 ml-2 btn btn-primary" value="Create Person" />
    <form>
</div>

<div class="container-fluid">
    <table class="table table-striped table-sm" id="my_persons">
        <thead>
            <tr>
                <th>Nick name</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Adress</th>
            </tr>
        </thead>
        <tbody>
        {% for person in person %}
        <tr>
            <td>{{person.nick_name}}</td>
            <td>{{person.first_name}}</td>
            <td>{{person.last_name}}</td>
            <td>{{person.address}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}
{% block javascript %}
<script>
    $("#person-form").submit(function (e) {
        e.preventDefault();
        // serialize data untuk mengirimkan data form
        var serializeData   = $(this).serialize();
        // panggil POST ajax
        $.ajax({
            type: 'POST',
            url: "{% url 'post_person' %}",
            data: serializeData,
            success: function (response) {
                // sukses membuat objek
                // bersihkan form
                $("#person-form").trigger('reset')
                // fokuskan ke nickname input
                $("#id_nick_name").focus();

                // tampilakn person baru ke tabel
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#my_person tbody").prepend(
                    `<tr>
                        <td>${fields["nick_name"]||""}</td>
                        <td>${fields["first_name"]||""}</td>
                        <td>${fields["last_name"]||""}</td>
                        <td>${fields["address"]||""}</td>
                    </tr>`
                )
            },
            error: function (response) {
                // beritahu kesalahan
                alert(response["responseJSON"]["error"]);
            }
        })
    })

    $("#id_nick_name").focusout(function (e) {
        e.preventDefault();
        // ambil nickname
        var nick_name = $(this).val();
        // GET AJAX request
        $.ajax({
            type: 'GET',
            url: "{% url 'validate_nickname' %}",
            data: {"nick_name": nick_name},
            success: function (response) {
                if(!response["valid"]) {
                    alert("Gak bisa bikin Person dengan nick name yang sama");
                    var nickName = $("#id_nick_name");
                    nickName.val("")
                    nickName.focus()
                }
            },
            error: function (response) {
                console.log(response)
            }
        })
    })
</script>
{% endblock javascript %}